#!/usr/bin/env bash
# DEV LOOP INSTALLER for the cs2-server-manager test box. NOT for production and never
# shipped in the release zip: it builds, STOPS `csm` server $CSM_SERVER_ID, WIPES Ready Up DB
# state (ru_active_* settings, readyup_admins) and attaches the console.
# Release installs: extract the zip into game/csgo and run readyup/tools/patch_gameinfo.py
# (or readyup/tools/install.sh); see docs/INSTALL.md.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Dev workflow defaults (cs2-server-manager).
CSM_SERVER_ID="${CSM_SERVER_ID:-1}"

run_as_root() {
  if [[ "$(id -u)" == "0" ]]; then
    "$@"
  else
    sudo "$@"
  fi
}
# Search path to install to + to add in gameinfo.gi.
# Default matches the "extract zip into game/csgo" layout.
GAME_PATH="${GAME_PATH:-}"
if [[ -z "$GAME_PATH" && -n "${GAME_NAME:-}" ]]; then
  # Backwards compatibility with the earlier env var name.
  GAME_PATH="$GAME_NAME"
fi
GAME_PATH="${GAME_PATH:-csgo/readyup}"

AUTO_BUILD=1
AUTO_SUDO=0
READYUP_DEBUG_CFG="${READYUP_DEBUG_CFG:-0}"

DEFAULT_CS2_ROOT="/home/cs2servermanager/server-1"

ARGS=()
for arg in "$@"; do
  case "$arg" in
    --build) AUTO_BUILD=1 ;;
    --no-build) AUTO_BUILD=0 ;;
    --debug) READYUP_DEBUG_CFG=1 ;;
    -h|--help) ARGS+=("--help") ;;
    *) ARGS+=("$arg") ;;
  esac
done
set -- "${ARGS[@]}"

if [[ "${1:-}" == "--help" ]]; then
  echo "Usage: $0 [/path/to/cs2/root]"
  echo "Default: $DEFAULT_CS2_ROOT"
  echo ""
  echo "Options:"
  echo "  --no-build   Skip building (repo checkout only)"
  echo "  --debug      Enable Ready Up shim debug logs"
  exit 0
fi

CS2_ROOT="${1:-$DEFAULT_CS2_ROOT}"
GAME_DIR="$CS2_ROOT/game"
CSGO_DIR="$GAME_DIR/csgo"
TARGET_DIR="$GAME_DIR/$GAME_PATH"
CSGO_CFG_DIR="$CSGO_DIR/cfg"

if [[ ! -d "$GAME_DIR" ]]; then
  echo "ERROR: '$GAME_DIR' does not exist (is this the CS2 root?)" >&2
  exit 1
fi

# Dev default: stop server before installing so it reloads cleanly.
if command -v csm >/dev/null 2>&1; then
  echo "Stopping server via cs2-server-manager: csm stop $CSM_SERVER_ID"
  run_as_root csm stop "$CSM_SERVER_ID"
fi

# If we're in a repo checkout (build.sh exists), build before installing.
if [[ "$AUTO_BUILD" == "1" && -f "$ROOT_DIR/build.sh" ]]; then
  if [[ "$(id -u)" == "0" && -n "${SUDO_USER:-}" ]]; then
    # Avoid leaving root-owned build artifacts in the repo.
    sudo -u "$SUDO_USER" -E "$ROOT_DIR/build.sh"
  else
    "$ROOT_DIR/build.sh"
  fi
fi

SERVER_SO=""
for candidate in \
  "$ROOT_DIR/build/libserver.so" \
  "$ROOT_DIR/bin/linuxsteamrt64/libserver.so"
do
  if [[ -f "$candidate" ]]; then
    SERVER_SO="$candidate"
    break
  fi
done

PATCHER=""
for candidate in \
  "$ROOT_DIR/scripts/patch_gameinfo.py" \
  "$ROOT_DIR/tools/patch_gameinfo.py"
do
  if [[ -f "$candidate" ]]; then
    PATCHER="$candidate"
    break
  fi
done

# If we need write access, auto-elevate after building.
if [[ "$(id -u)" != "0" ]]; then
  if [[ ! -w "$GAME_DIR" || ! -w "$CSGO_DIR" ]]; then
    echo "ERROR: insufficient permissions to install into '$CS2_ROOT'." >&2
    echo "Re-run with sudo, e.g.:" >&2
    echo "  sudo $0 --no-build $CS2_ROOT" >&2
    exit 1
  fi
fi

if [[ -z "$SERVER_SO" ]]; then
  echo "ERROR: Could not find libserver.so to install." >&2
  echo "Looked for:" >&2
  echo "  - $ROOT_DIR/build/libserver.so (dev build)" >&2
  echo "  - $ROOT_DIR/bin/linuxsteamrt64/libserver.so (release zip layout)" >&2
  exit 1
fi

if [[ -z "$PATCHER" ]]; then
  echo "ERROR: Could not find patch_gameinfo.py." >&2
  echo "Looked for:" >&2
  echo "  - $ROOT_DIR/scripts/patch_gameinfo.py (repo layout)" >&2
  echo "  - $ROOT_DIR/tools/patch_gameinfo.py (release zip layout)" >&2
  exit 1
fi

# Install ownership: match the existing game directory ownership.
OWNER_UID="$(stat -c '%u' "$GAME_DIR")"
OWNER_GID="$(stat -c '%g' "$GAME_DIR")"

mkdir -p "$TARGET_DIR/bin/linuxsteamrt64"
cp -f "$SERVER_SO" "$TARGET_DIR/bin/linuxsteamrt64/libserver.so"
chmod 755 "$TARGET_DIR/bin/linuxsteamrt64/libserver.so" || true

# Write Ready Up runtime config next to the shim. We use this because csm/tmux
# does not reliably propagate environment variables to the server process.
READYUP_CFG_PATH="$TARGET_DIR/bin/linuxsteamrt64/readyup.cfg"
if [[ ! -f "$READYUP_CFG_PATH" ]]; then
  cat >"$READYUP_CFG_PATH" <<EOF
# Ready Up runtime config (generated by install.sh)
#
# Notes:
# - This file is only generated if missing. Once created, admins are expected to
#   edit it, and you can apply changes in-game with: .ru reload
#
# Booleans: 0/1 (or n/y, f/t).
debug=$READYUP_DEBUG_CFG
chat_debug=$READYUP_DEBUG_CFG
banner=1
# Per-player "Ready Up is live" center screen on first T/CT join each map.
welcome=1
# Per-player center ready list (scrim/match warmup) and knife side-pick panel.
ready_hud=1
# Header of the welcome card + ready HUD: optional logo (image URL; empty = none)
# and brand text. Test what the client renders with `.ru hudtest 1..7` (admin).
hud_brand=Auto Tournament
hud_logo_url=
# Scrims: knife round once everyone is ready; the winning side types .stay or
# .switch within knife_pick_seconds (no pick = stay). 0 = straight to live.
scrim_knife=1
knife_pick_seconds=60

# DEBUG ONLY: bots on CT/T count as always-ready scrim players, so one human can
# test ready -> live with bots (bot-only teams also auto-confirm .unpause).
# Never enable on a real match server.
# (env override: READYUP_DEV_BOTS_READY)
dev_bots_ready=0

# Prefixes (supports ChatColors tokens like <DarkRed>, <Default>, <LightBlue>, <Orange>, ...).
# Ready Up always adds a single space after the prefix in output.
chat_prefix=<DarkRed>[Ready Up]<Default>
admin_prefix=<DarkRed>[Admin]<Default>
EOF
else
  echo "Keeping existing Ready Up config: $READYUP_CFG_PATH"
fi

# Write DB config for shared admin storage (best-effort default).
# Only create if missing, so you can edit it once and keep it.
if [[ ! -f "$TARGET_DIR/bin/linuxsteamrt64/readyup_db.json" ]]; then
  cat >"$TARGET_DIR/bin/linuxsteamrt64/readyup_db.json" <<'EOF'
{
  "conninfo": "host=127.0.0.1 port=5449 dbname=readyup user=readyup password=readyup sslmode=disable"
}
EOF
fi

# Dev safety: wipe persisted RU state each install so stale recovery can't trigger.
# This is best-effort (won't fail install if DB tooling isn't present).
READYUP_DB_JSON="$TARGET_DIR/bin/linuxsteamrt64/readyup_db.json"
if [[ -f "$READYUP_DB_JSON" ]] && command -v python3 >/dev/null 2>&1; then
  READYUP_DB_CONNINFO="$(
    python3 - <<'PY' "$READYUP_DB_JSON" 2>/dev/null || true
import json, sys
path = sys.argv[1]
try:
  with open(path, "r", encoding="utf-8") as f:
    j = json.load(f)
  print(j.get("conninfo", ""))
except Exception:
  pass
PY
  )"

  if [[ -n "$READYUP_DB_CONNINFO" ]] && command -v psql >/dev/null 2>&1; then
    echo "Wiping Ready Up DB state (readyup_settings/readyup_admins) ..."
    # Only clear RU-owned tables/keys (avoid dropping the whole database).
    # This prevents an old match (ru_active_*) from being recovered after reinstall.
    psql "$READYUP_DB_CONNINFO" -v ON_ERROR_STOP=1 -qAt <<'SQL' >/dev/null 2>&1 || true
DO $$
BEGIN
  IF to_regclass('public.readyup_settings') IS NOT NULL THEN
    DELETE FROM readyup_settings WHERE key LIKE 'ru_active_%';
  END IF;
  IF to_regclass('public.readyup_admins') IS NOT NULL THEN
    TRUNCATE readyup_admins;
  END IF;
END $$;
SQL
  fi
fi

# Engine surface (signatures + identity anchors) is repo-owned and embedded in the shim.
# Install the matching on-disk copy next to it so the two never drift; the shim prefers
# this file, so an operator can hotfix a signature without rebuilding.
# The old CounterStrikeSharp CDN cache (readyup_gamedata.json) is no longer used.
ENGINE_SURFACE_SRC=""
for cand in "$ROOT_DIR/gamedata/engine-surface.json" "$ROOT_DIR/bin/linuxsteamrt64/engine-surface.json"; do
  if [[ -f "$cand" ]]; then ENGINE_SURFACE_SRC="$cand"; break; fi
done
if [[ -n "$ENGINE_SURFACE_SRC" ]]; then
  cp -f "$ENGINE_SURFACE_SRC" "$TARGET_DIR/bin/linuxsteamrt64/engine-surface.json"
  echo "Installed engine surface: $TARGET_DIR/bin/linuxsteamrt64/engine-surface.json"
else
  # Don't leave a stale copy overriding the shim's embedded one.
  rm -f "$TARGET_DIR/bin/linuxsteamrt64/engine-surface.json" || true
  echo "Using the engine surface embedded in the shim."
fi
if [[ -f "$TARGET_DIR/bin/linuxsteamrt64/readyup_gamedata.json" ]]; then
  echo "Note: $TARGET_DIR/bin/linuxsteamrt64/readyup_gamedata.json is no longer read and can be deleted."
fi

# If running under sudo/root, ensure resulting files are owned by the server user.
if [[ "$(id -u)" == "0" ]]; then
  chown -R "$OWNER_UID:$OWNER_GID" "$TARGET_DIR" || true
fi

echo "Installed shim to: $TARGET_DIR/bin/linuxsteamrt64/libserver.so"
echo "Note: shim will load real libserver.so from csgo path automatically."

# Dev convenience: create a `ru` alias command (cfg) showing build/health.
# We do it via cfg (not native ConCommand) to avoid ABI issues / crashes.
READYUP_BUILD="$(cd "$ROOT_DIR" && (git rev-parse --short HEAD 2>/dev/null || true))"
READYUP_BUILD="${READYUP_BUILD:-unknown}"
mkdir -p "$CSGO_CFG_DIR"

# Optional: install MatchZy-style Ready Up mode cfg templates.
# These are only copied if missing so local edits are preserved.
READYUP_MODE_CFG_SRC="$ROOT_DIR/cfg/ReadyUp"
READYUP_MODE_CFG_DST="$CSGO_CFG_DIR/ReadyUp"
if [[ -d "$READYUP_MODE_CFG_SRC" ]]; then
  mkdir -p "$READYUP_MODE_CFG_DST"
  for f in "$READYUP_MODE_CFG_SRC"/*.cfg; do
    [[ -f "$f" ]] || continue
    base="$(basename "$f")"
    if [[ ! -f "$READYUP_MODE_CFG_DST/$base" ]]; then
      cp -f "$f" "$READYUP_MODE_CFG_DST/$base"
    fi
  done
fi

cat >"$CSGO_CFG_DIR/readyup_autoexec.cfg" <<'EOF'
// Ready Up dev helpers
// `ru` is handled natively by Ready Up (console hook), so we keep cfg minimal.

// Reload cfg (convenience).
alias ru_reload "exec readyup_autoexec; echo [ReadyUp] cfg reloaded"

// Make built-in server log lines visible in console.
log on
sv_logecho 1
EOF

# Replace placeholders (avoid quoting artifacts in CS2 console output).
sed -i \
  -e "s|READYUP_BUILD_PLACEHOLDER|$READYUP_BUILD|g" \
  -e "s|READYUP_SHIM_PLACEHOLDER|$TARGET_DIR/bin/linuxsteamrt64/libserver.so|g" \
  "$CSGO_CFG_DIR/readyup_autoexec.cfg"

# Ensure server.cfg loads Ready Up aliases.
if [[ -f "$CSGO_CFG_DIR/server.cfg" ]]; then
  if ! grep -qE '^[[:space:]]*exec[[:space:]]+readyup_autoexec[[:space:]]*$' "$CSGO_CFG_DIR/server.cfg"; then
    printf '\nexec readyup_autoexec\n' >>"$CSGO_CFG_DIR/server.cfg"
  fi
else
  # If server.cfg doesn't exist, create one that loads it.
  printf 'exec readyup_autoexec\n' >"$CSGO_CFG_DIR/server.cfg"
fi

if [[ -f "$CSGO_DIR/gameinfo.gi" ]]; then
  if [[ -w "$CSGO_DIR/gameinfo.gi" ]]; then
    python3 "$PATCHER" "$CSGO_DIR/gameinfo.gi" --game "$GAME_PATH"
  else
    echo "WARNING: '$CSGO_DIR/gameinfo.gi' is not writable. Re-run with sudo or patch manually:"
    echo "  Add:    Game    $GAME_PATH"
    echo "  Before: Game    csgo"
  fi
fi
if [[ -f "$CSGO_DIR/gameinfo_branchspecific.gi" ]]; then
  if [[ -w "$CSGO_DIR/gameinfo_branchspecific.gi" ]]; then
    python3 "$PATCHER" "$CSGO_DIR/gameinfo_branchspecific.gi" --game "$GAME_PATH"
  else
    echo "WARNING: '$CSGO_DIR/gameinfo_branchspecific.gi' is not writable. Re-run with sudo or patch manually:"
    echo "  Add:    Game    $GAME_PATH"
    echo "  Before: Game    csgo"
  fi
fi

echo "Done."

# Dev default: attach to console at the end.
if command -v csm >/dev/null 2>&1; then
  echo "Attaching server console: csm debug $CSM_SERVER_ID"
  run_as_root csm debug "$CSM_SERVER_ID"
fi
