#!/usr/bin/env python3
"""Regenerate plugins/skins/legacy_paint_kits.inc from CS2's items_game.txt.

A paint kit with `"use_legacy_model" "1"` was authored for the CS:GO weapon UVs; in CS2 it only
looks right on the weapon's legacy model, selected with bodygroup "body" = 1.

items_game.txt lives in game/csgo/pak01_dir.vpk (scripts/items/items_game.txt). Extract it with
any VPK tool, then:

    plugins/skins/gen_legacy_paint_kits.py path/to/items_game.txt > plugins/skins/legacy_paint_kits.inc
"""
import re
import sys


def parse_kv(text):
    toks = re.findall(r'"((?:[^"\\]|\\.)*)"|([{}])', text)

    def parse(i):
        out = []
        while i < len(toks):
            s, br = toks[i]
            if br == "}":
                return out, i + 1
            key = s
            i += 1
            s2, br2 = toks[i]
            if br2 == "{":
                v, i = parse(i + 1)
                out.append((key, v))
            else:
                out.append((key, s2))
                i += 1
        return out, i

    root, _ = parse(2)  # skip `"items_game" {`
    return root


def main():
    text = open(sys.argv[1], encoding="utf-8", errors="replace").read()
    version = sys.argv[2] if len(sys.argv) > 2 else "unknown"
    legacy = set()
    total = 0
    for key, section in parse_kv(text):
        if key != "paint_kits":
            continue
        for pid, body in section:
            if not isinstance(body, list):
                continue
            total += 1
            kv = {a: b for a, b in body if not isinstance(b, list)}
            if kv.get("use_legacy_model") == "1":
                legacy.add(int(pid))
    ids = sorted(legacy)
    print("// Generated by plugins/skins/gen_legacy_paint_kits.py from items_game.txt (CS2 %s)." % version)
    print("// Paint kits with \"use_legacy_model\" \"1\": %d of %d. Sorted; used with std::binary_search." % (len(ids), total))
    for i in range(0, len(ids), 16):
        print("    " + ", ".join(str(x) for x in ids[i:i + 16]) + ",")


if __name__ == "__main__":
    main()
